#release configuration
#Thu Apr 02 19:09:14 EDT 2026
projectVersionPolicyId=default
project.scm.org.apache.jspwiki\:jspwiki-bootstrap.empty=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
project.scm.org.apache.jspwiki\:jspwiki-main.empty=true
project.scm.org.apache.jspwiki\:jspwiki-kendra-searchprovider.empty=true
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
project.scm.org.apache.jspwiki\:jspwiki-util.empty=true
project.scm.org.apache.jspwiki.it\:jspwiki-selenide-tests.empty=true
project.scm.org.apache.jspwiki.it\:jspwiki-it-test-cma-jdbc.empty=true
project.scm.org.apache.jspwiki\:jspwiki-war.empty=true
project.scm.org.apache.jspwiki.wikipages\:jspwiki-wikipages-fr.empty=true
project.scm.org.apache.jspwiki\:jspwiki-cache.empty=true
releaseStrategyId=default
scm.commentPrefix=[maven-release-plugin] 
project.scm.org.apache.jspwiki\:jspwiki-portable.empty=true
project.scm.org.apache.jspwiki.wikipages\:jspwiki-wikipages-pt_BR.empty=true
project.scm.org.apache.jspwiki\:jspwiki-api.empty=true
completedPhase=check-poms
project.scm.org.apache.jspwiki.wikipages\:jspwiki-wikipages-it.empty=true
project.scm.org.apache.jspwiki\:jspwiki-http.empty=true
project.scm.org.apache.jspwiki.wikipages\:jspwiki-wikipages-en.empty=true
project.scm.org.apache.jspwiki.it\:jspwiki-it-builder.empty=true
preparationGoals=clean verify
project.scm.org.apache.jspwiki.wikipages\:jspwiki-wikipages-fi.empty=true
exec.pomFileName=pom.xml
project.scm.org.apache.jspwiki\:jspwiki-builder.developerConnection=scm\:git\:https\://github.com/apache/jspwiki.git
project.scm.org.apache.jspwiki\:jspwiki-builder.tag=jspwiki-builder-2.12.4-RC1
project.scm.org.apache.jspwiki\:jspwiki-bom.empty=true
project.scm.org.apache.jspwiki\:jspwiki-210-test-adaptees.empty=true
project.scm.org.apache.jspwiki\:jspwiki-tika-searchprovider.empty=true
project.scm.org.apache.jspwiki.wikipages\:jspwiki-wikipages-nl.empty=true
pinExternals=false
project.scm.org.apache.jspwiki.wikipages\:jspwiki-wikipages-zh_CN.empty=true
pushChanges=true
project.scm.org.apache.jspwiki.wikipages\:jspwiki-wikipages-de.empty=true
project.scm.org.apache.jspwiki.it\:jspwiki-it-test-cma.empty=true
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
remoteTagging=true
project.scm.org.apache.jspwiki.it\:jspwiki-it-test-custom.empty=true
project.scm.org.apache.jspwiki\:jspwiki-markdown.empty=true
project.scm.org.apache.jspwiki\:jspwiki-event.empty=true
project.scm.org.apache.jspwiki.wikipages\:jspwiki-wikipages-ru.empty=true
project.scm.org.apache.jspwiki.it\:jspwiki-it-test-custom-absolute-urls.empty=true
project.scm.org.apache.jspwiki.wikipages\:jspwiki-wikipages-builder.empty=true
project.scm.org.apache.jspwiki\:jspwiki-builder.url=https\://github.com/apache/jspwiki
scm.url=scm\:git\:https\://github.com/apache/jspwiki.git
project.scm.org.apache.jspwiki\:jspwiki-210-adapters.empty=true
scm.developmentCommitComment=@{prefix} prepare for next development iteration
project.scm.org.apache.jspwiki\:jspwiki-builder.connection=scm\:git\:https\://github.com/apache/jspwiki.git
project.scm.org.apache.jspwiki.it\:jspwiki-it-test-custom-jdbc.empty=true
scm.tagNameFormat=@{project.artifactId}-@{project.version}
project.scm.org.apache.jspwiki.wikipages\:jspwiki-wikipages-es.empty=true
project.scm.org.apache.jspwiki\:jspwiki-wysiwyg.empty=true
exec.snapshotReleasePluginAllowed=false
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
