/*!
    JSPWiki - a JSP-based WikiWiki clone.

    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements.  See the NOTICE file
    distributed with this work for additional information
    regarding copyright ownership.  The ASF licenses this file
    to you under the Apache License, Version 2.0 (the
    "License"); fyou may not use this file except in compliance
    with the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.
*/
/*
Class: SnipEditor.Sections
    This dialog displays the list of page sections.
    A page section includes the header

    (all) - allows to select all sections (auto generated)
    start-of-page - only present when first section starts on an offset > 0
    section1..n - section titles, with indentation level depending on their weight

    The set of sections is generated by the parseSections() callback handler.
    This parser returns an array of section 'descriptors':
>    [ {title:text, start:char-offset, indent:indentation-level}, ... ]

    Clicking an entry triggers the updateSections() callback handler.
    FIXME: why not fire an onAction event (similar to other dialogs)

Depends:
    Dialog.Selection


TODO
Convert to Bootstrap DropDown, 
Wiki.Sections.js

wiki.add('[data-sections]',  Snipe.Sections); 

section = container.getElement('.section');
if(section) new Snip.Sections( snipe, selected string, parser);
    
});
//need snipe object
//need "selected" string -- create yourself ...

    this.snipe = options.snipe;
    this.parser = options.parser;
    new Wiki.Sections( snipe );
    
snipe.addEvent('change', this.change.bind(this))
snipe.addEvent('keyup', this.change.bind(this))

dropdown.addEvent('mouseenter', this.show.bind(this))
dropdown.onHover(...); //hover effect
//dropdown.addEvent('mouseleave')

);

*/

Snipe.Sections = new Class({

    Extends:Dialog.Selection,

    options: {
        //main:textarea
        //work:textarea
        //selected: selected item: all,s-1,s0..sn
        //parser: function
        all: "( all )".localize(),
        startOfPage: "Start of Page".localize()
    },

    initialize: function(options){

        var self = this,
            onChange = self.onChange.bind(self);

        this.setClass('.sections',options);
        self.parent(options);

        self.parse();
        self.action();

        //can be hooked up by the SnipEditor.Commands
        /*self.dialogDefinition = [Dialog.Selection, {
            selected: self.options.selected,
            onOpen: self.onOpen,
            onAction: self.onAction
        }];*/

        //FIXME !! keyup
        self.options.work.addEvents({ change:onChange, keyup:onChange });

    },

    /*
    Function: parse
        Invoke the external parser on the contents of the main textarea.
        This external parser should return an array with an entry for each section:
        [ {title:text, start:char-offset, depth:nesting level}, ... ]

        >        0 : ( all )                       => title=All => cursor=NaN
        >        1 : start-of-page (if applicable) => title=s-1 => cursor=-1
        >        2..n : page sections              => title=s0..sn => cursor=0..n

    */
    parse: function(){
        this.sections = this.options.parser( this.options.main.value );
    },

    /*
    Function: onOpen
        UPDATE/RFEFRESH the textarea section dialog.
    */
    //onOpen: function( dialog ){
    show: function( ){

        //console.log("Sections: show");
        var options = this.options,
            data = { all: options.all },
            sections = this.sections;

        if( sections[0] /*.length > 0*/ ){
            if( sections[0].start>0 ){ data['s-1'] = options.startOfPage }
            sections.each( function(item, idx){ data['s'+idx] = item.title.trunc(36); });
        }

        //dialog.setBody( data ).getItems().each(function(el){
        this.setBody( data ).getItems().each(function(el){
            var t = el.title.slice(1).toInt();
            if( t>=0 ){ el.setStyle('padding-left',(.5+sections[t].depth)+'em'); }
        });

        this.parent(); //invoke parent's show
    },

    /*
    Function: onChange
        Make sure that changes to the work textarea are propagated to the main textarea.
        This functions handles the correct insertion of the changed section into the main
        textarea.
    */
    onChange: function(){

        //console.log("Sections: onChange");
        var self = this,
            main = self.options.main,
            work = self.options.work.value,
            sections = self.sections,
            s = main.value,
            //insert \n to ensure the next section always starts on a new line.
            linefeed = (work.slice(-1) != '\n')  ? '\n' : '';

        //console.log('change txta: from='+sections.begin+ ' end='+sections.end);
        main.value = s.slice(0, self.begin) + work + linefeed + s.slice(self.end);
        self.end = self.begin + work.length;

        self.parse();
    },

    /*
    Function: onAction
        This function copies the selected section from the main to the work textarea.
        It is invoked at initialization and through the dialog onAction click handler.

    Arguments:
        cursor - index of selected section: all, -1, 0..n
    */
    //onAction:function( item ){

    /*
    setValue: function(value){
    },
    action: function(item){
        var value = item.get('title');
        this.setValue(value).parent(value);
    },
    */
    action:function( item ){

        var self = this,
            main = self.options.main.value,
            sections = self.sections,
            begin = 0,
            end = main.length;

        if( item ){

            item = item.replace(/^s/,'').toInt();

            if( item == -1 ){

                //show the Start Of Page, prior to the first real section
                end = sections[0].start;

            } else if(item >= 0  && sections[item] /*item < sections.length*/ ){

                begin = sections[item].start;
                //if( item+1 < sections.length ){ end = sections[item+1].start; }
                if( sections[item+1] ){ end = sections[item+1].start; }

            }
        }

        self.options.work.value = main.slice(begin, end);
        self.begin = begin;
        self.end = end;
        //console.log("Section: onAction " + item + " "+self.begin+" "+self.end);

        //checkme
        if( item ) self.parent(item);
    }
});
