/**
 * 
 */
package com.ecyrd.jspwiki.action;

import java.lang.annotation.*;

/**
 * WikiActionBean annotation that specifies the pattern to use for URLs generated by 
 * the {@link WikiActionBean#getURL()}.
 * @author Andrew Jaquith
 */
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE})
@Documented
@Inherited
public @interface WikiUrlPattern
{
    /**
     * The request context for looking up an ActionBean.
     * If not supplied and the class is a subclass of {@link AbstractActionBean}
     * the superclass default value will be inherited ("none").
     */
    String value();
}
