package org.apache.wiki.filters;

import net.sourceforge.stripes.action.Resolution;
import net.sourceforge.stripes.controller.ExecutionContext;
import net.sourceforge.stripes.controller.Interceptor;
import net.sourceforge.stripes.controller.Intercepts;
import net.sourceforge.stripes.controller.LifecycleStage;

import org.apache.wiki.action.WikiActionBean;

/**
 * Stripes Interceptor that ensures that SpamFilter algorithms are applied to
 * events annotated with the {@link SpamProtect} annotation. This class
 * processes form parameters generated by the
 * {@link org.apache.wiki.tags.SpamProtectTag} tag. It fires after the
 * {@link LifecycleStage#HandlerResolution} stage; that is, after ActionBean and
 * event handler resolution, but before parameter binding.
 */
@Intercepts( { LifecycleStage.HandlerResolution } )
public class SpamInterceptor implements Interceptor
{
    /** Request parameter containing the UTF8 check. */
    public static final String REQ_ENCODING_CHECK = "encodingcheck";

    /** Request parameter containing the encoded payload. */
    public static final String REQ_SPAM_PARAM = "____sp____";

    /**
     * Validates spam parameters contained in any requests targeting an
     * ActionBean method annotated with the {@link SpamProtect} annotation. This
     * simply delegates to {@link SpamFilter#validateSpamParams(WikiActionBean)}
     * and {@link SpamFilter#validateUTF8Param(WikiActionBean)} in sequence, and
     * returns any Resolutions they generate. If the targeted ActionBean event
     * is not annotated, this method returns <code>null</code>.
     */
    public Resolution intercept( ExecutionContext context ) throws Exception
    {
        // Execute all other interceptors first
        context.proceed();

        // Validate spam token/trap params
        WikiActionBean actionBean = (WikiActionBean) context.getActionBean();
        Resolution r = SpamFilter.validateSpamParams( actionBean );

        // Validate non-Latin1 param
        if( r != null )
        {
            r = SpamFilter.validateUTF8Param( actionBean );
        }
        return r;
    }

}
