
package com.ecyrd.jspwiki;

import junit.framework.*;
import java.util.*;

import org.apache.log4j.*;

import com.ecyrd.jspwiki.providers.*;
import com.ecyrd.jspwiki.util.MailUtil;

/**
 * This test is not integrated into any TestSuite yet, because I don't know how
 * to really assert if a mail was sent etc. (setup would be to complicated yet). Therefore
 * replace the static TEST variables with your configuration and test by hand: execute
 * testSendMail and see if you get the mail at the adress you indicate in "TEST_RECEIVER".
 * 
 * @author Christoph Sauer
 *
 */
public class MailUtilTest extends TestCase
{
    Properties m_props = new Properties();

    WikiContext     m_context;

    static final String PAGE_NAME = "TestPage";
    
    static final String TEST_HOST = "mail.mydomain.org";
    static final String TEST_PORT = "587";
    static final String TEST_ACCOUNT = "myaccount";
    static final String TEST_PASSWORD = "changeit";
    
    static final String TEST_RECEIVER = "someone@somewhere.org";
    static final String TEST_SENDER = "homer.simpson@burns.com";
    
    public MailUtilTest( String s )
    {
        super( s );
    }

    public void setUp()
        throws Exception
    {
        m_props.load( TestEngine.findTestProperties() );
        PropertyConfigurator.configure(m_props);
        
        m_props.setProperty(MailUtil.MAIL_HOST, TEST_HOST);
        m_props.setProperty(MailUtil.MAIL_PORT, TEST_PORT);
        m_props.setProperty(MailUtil.MAIL_ACCOUNT, TEST_ACCOUNT);
        m_props.setProperty(MailUtil.MAIL_PASSWORD, TEST_PASSWORD);
        m_props.setProperty(MailUtil.MAIL_SENDER, TEST_SENDER);

        TestEngine testEngine = new TestEngine( m_props );
        
        m_context = new WikiContext( testEngine,
                                     new WikiPage( testEngine, PAGE_NAME ) );
    }

    public void tearDown()
    {
    }

    public void testProperties() 
    {
        String sender = m_context.getEngine().getWikiProperties().getProperty(MailUtil.MAIL_SENDER);
        assertTrue(sender.equals("homer.simpson@burns.com"));
        String account = m_context.getEngine().getWikiProperties().getProperty(MailUtil.MAIL_ACCOUNT);
        assertTrue(account.equals("csauer.steinbeis"));
    }
    
    public void testSendMail()
    {
        m_props.setProperty( "jspwiki.usePageCache", "true" );

        System.out.println(m_context.getEngine().getWikiProperties().getProperty(MailUtil.MAIL_ACCOUNT));

        try
        {
            MailUtil.sendMessage(m_context, 
                                 TEST_RECEIVER, 
                                 "testSendmail()", 
                                 "This is the content of a Testmail generated by MailUtilTest");            
        }
        catch (Exception e)
        {
            // TODO: handle exception
            e.printStackTrace();
            assertTrue(false);
        }
        
        //assertTrue( m.getProvider() instanceof CachingProvider );
    }

    public static Test suite()
    {
        return new TestSuite( MailUtilTest.class );
    }

}
